### ISSUE TITLE
Subcolumns must be ordered

### ISSUE THREAD

**Issue by tcmj** [tcmj/tcmj-pug-enums#15]
if you define subcolumns the order bust be sorted
eg. 3,4,5 works
4,5,3 does not work

```com.tcmj.pug.enums.model.ClassCreationException: java.lang.IllegalArgumentException: unused arguments: expected 2, received 3
	at com.tcmj.pug.enums.builder.impl.JavaPoetEnumBuilder.build(JavaPoetEnumBuilder.java:80)
	at com.tcmj.pug.enums.api.fluent.Fluent.build(Fluent.java:151)
	at com.tcmj.pug.enums.example.fluent.WikipediaExample3.main(WikipediaExample3.java:28)
Caused by: java.lang.IllegalArgumentException: unused arguments: expected 2, received 3
	at com.squareup.javapoet.Util.checkArgument(Util.java:64)
	at com.squareup.javapoet.CodeBlock$Builder.add(CodeBlock.java:243)
	at com.squareup.javapoet.TypeSpec.anonymousClassBuilder(TypeSpec.java:115)
	at com.tcmj.pug.enums.builder.impl.JavaPoetEnumBuilder.writeEnumConstants(JavaPoetEnumBuilder.java:156)
	at com.tcmj.pug.enums.builder.impl.JavaPoetEnumBuilder.build(JavaPoetEnumBuilder.java:45)```

**Comment by tcmj** [comment]
possible cause might be in this method: isColumnInArray of class URLHtmlDataProvider ??

**Comment by tcmj** [comment]
We start by implementing some unit tests which describes the expected behavour
